using Content.Goobstation.Shared.Phone;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Goobstation.Client.Phone;

[GenerateTypedNameReferences]
public sealed partial class PhoneMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly AudioSystem _audioSystem;

    private bool _playState;
    private float _lockTimer;
    private EntityUid? _audio;

    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<ProtoId<JukeboxPrototype>>? OnTrackSelected;
    public event Action<float>? OnSetTime;
    public event Action<float>? OnSetVolume;

    public PhoneMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        // Настройка списка треков
        TrackList.OnItemSelected += args =>
        {
            if (TrackList[args.ItemIndex].Metadata is not string trackId)
                return;
            OnTrackSelected?.Invoke(trackId);
        };

        // Настройка кнопок управления
        PlayButton.OnPressed += _ => OnPlayPressed?.Invoke(!_playState);
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
        PlaybackSlider.OnReleased += OnPlaybackSliderReleased;

        // Настройка громкости
        VolumeSlider.OnValueChanged += args =>
        {
            var pct = (int)(args.Value * 100);
            VolumeLabel.Text = $"{pct}%";
            OnSetVolume?.Invoke(args.Value);
        };

        SetPlayPauseButton(false, force: true);
    }

    private void OnPlaybackSliderReleased(Slider slider)
    {
        OnSetTime?.Invoke(slider.Value);
        _lockTimer = 0.5f;
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    public void Populate(IEnumerable<JukeboxPrototype> tracks)
    {
        TrackList.Clear();
        foreach (var track in tracks)
            TrackList.AddItem(track.Name, metadata: track.ID);
    }

    public void SetSelectedTrack(string name, float length)
    {
        TrackName.Text = string.IsNullOrEmpty(name) ? "---" : name;
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    public void SetVolume(float volume)
    {
        VolumeSlider.SetValueWithoutEvent(volume);
        VolumeLabel.Text = $"{(int)(volume * 100)}%";
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force) return;
        _playState = playing;
        PlayButton.Text = playing ? "⏸ Пауза" : "▶ Играть";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
            _lockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            var length = _audioSystem.GetAudioLength(audio.FileName);
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {length:mm\:ss}";

            if (!PlaybackSlider.Grabbed)
                PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        }
        else
        {
            DurationLabel.Text = "00:00 / 00:00";
            if (!PlaybackSlider.Grabbed)
                PlaybackSlider.SetValueWithoutEvent(0f);
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }
}
