// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.PhraseWheel;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.PhraseWheel;

[GenerateTypedNameReferences]
public sealed partial class PhraseWheelWindow : FancyWindow
{
    public event Action<PhraseWheelEntryPrototype>? OnPhraseSelected;

    public PhraseWheelWindow(IEnumerable<PhraseWheelEntryPrototype> phrases, IResourceCache resCache)
    {
        RobustXamlLoader.Load(this);

        // Группируем фразы по категориям
        var grouped = phrases
            .GroupBy(p => p.Category)
            .OrderBy(g => g.Key)
            .ToList();

        foreach (var group in grouped)
        {
            var scroll = new ScrollContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            var grid = new GridContainer
            {
                Columns = 4,
                HSeparationOverride = 4,
                VSeparationOverride = 4,
                Margin = new Thickness(4),
            };

            foreach (var phrase in group)
            {
                var btn = new PhraseWheelButton(phrase, resCache);
                btn.OnPressed += () => OnPhraseSelected?.Invoke(phrase);
                grid.AddChild(btn);
            }

            scroll.AddChild(grid);

            CategoryTabs.AddChild(scroll);
            CategoryTabs.SetTabTitle(CategoryTabs.ChildCount - 1, group.Key);
        }
    }
}

public sealed class PhraseWheelButton : Button
{
    public new event Action? OnPressed;

    public PhraseWheelButton(PhraseWheelEntryPrototype phrase, IResourceCache resCache)
    {
        MinSize = new Vector2(100, 90);
        MaxSize = new Vector2(120, 100);
        ToolTip = phrase.Text;

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 2,
            Margin = new Thickness(4),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        var icon = new TextureRect
        {
            MinSize = new Vector2(48, 48),
            MaxSize = new Vector2(48, 48),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Center,
        };

        try
        {
            var texture = phrase.Icon switch
            {
                SpriteSpecifier.Texture tex => resCache.GetResource<TextureResource>(tex.TexturePath).Texture,
                SpriteSpecifier.Rsi rsi => resCache.GetResource<RSIResource>(rsi.RsiPath).RSI[rsi.RsiState].Frame0,
                _ => null,
            };
            if (texture != null)
                icon.Texture = texture;
        }
        catch { }

        var displayText = string.IsNullOrEmpty(phrase.Label) ? phrase.Text : phrase.Label;
        if (displayText.Length > 14)
            displayText = displayText[..12] + "..";

        var label = new Label
        {
            Text = displayText,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.White,
            // Outline и Shadow удалены, так как не поддерживаются в коде вашей версии движка
        };

        vbox.AddChild(icon);
        vbox.AddChild(label);
        AddChild(vbox);

        OnButtonUp += _ => OnPressed?.Invoke();
    }
}
